import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'
	import {Form, TextField, Radio, RadioGroup, Switch, Slider} from '@adobe/react-spectrum'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.layout}>
        <nav className={styles.nav}>
          <a href="#" aria-current="page" >Account</a>
          <a href="#">Security</a>
          <a href="#">Privacy</a>
          <a href="#">Notifications</a>
        </nav>
        <main className={styles.main}>
          <h1>Account - settings</h1>

          <h3 id="label-3">Personal Information</h3>
          <Form maxWidth="size-3600" aria-labelledby="label-3">
            <TextField label="First Name" />
            <TextField label="Last Name" />
            <RadioGroup label="Favorite pet">
              <Radio value="dogs">Dogs</Radio>
              <Radio value="cats">Cats</Radio>
              <Radio value="dragons">Dragons</Radio>
            </RadioGroup>
            <Switch height={"8rem"}>Low power mode</Switch>
            <Slider label="Cookies to buy" defaultValue={12} />
          </Form>



        </main>
      </div>
      <footer>

      </footer>
    </div>
  )
}
